project:
  name: pipeline-dashboard
  regions:
    - us-east-1
tests:
  cloudwatch-dashboard:
    parameters:
      PipelinePattern: "*"
      BucketName: pipeline-dashboard-114930652771
      CodeKey: pipeline-dashboard.zip
    template: ./template.yml
