project:
  name: pipeline-dashboard
  regions:
    - us-east-1
tests:
  # test-cfn:
  #   template: ./test-cfn.yml
  cloudwatch-dashboard:
    parameters:
      PipelinePattern: "*"
      BucketName: pipeline-dashboard-114930652771
      CodeKey: pipeline-dashboard.zip
    template: ./template.yml
