project:
  name: pipeline-dashboard
  regions:
    - us-east-1
tests:
  test-cfn:
    template: ./test-cfn.yml
  # cloudwatch-dashboard:
  #   parameters:
  #     PipelinePattern: "*"
  #     BucketName: pipeline-dashboard-ACCOUNTID
  #     CodeKey: pipeline-dashboard.zip
  #   template: ./template.yml
